import { ArtDirectionSpec } from "./types.js";

export const BUILTIN_ART_PRESETS: Record<string, ArtDirectionSpec> = {
  cozy_farm_32: {
    project: "Cozy Farm",
    genre: "Farming RPG",
    camera: "top_down",
    baseTileSize: 32,
    characterScale: 32,
    outlineStyle: "dark_colored",
    palettePolicy: "ramp_extended",
    lightingDirection: "top_left",
    shadowPolicy: "warm_brown",
    saturation: "balanced",
    contrast: "medium",
    detailDensity: "readable_cluster",
    animationStyle: "snappy_chibi",
    uiStyle: "wooden_parchment_soft",
    backgroundStyle: "painterly_layered",
    forbiddenPatterns: ["pure_black_outlines", "pillow_shading", "orphan_pixels"],
    palette: [
      { name: "Dark Umber", hex: "#2b1c18", role: "outline" },
      { name: "Deep Earth", hex: "#4d2f23", role: "shadow" },
      { name: "Warm Oak", hex: "#7a4932", role: "base" },
      { name: "Caramel", hex: "#b56f45", role: "highlight" },
      { name: "Sand Gold", hex: "#e0a867", role: "accent" },
      { name: "Wheat Cream", hex: "#f5dcb3", role: "highlight" },
      { name: "Forest Dark", hex: "#1f3b25", role: "shadow" },
      { name: "Leaf Green", hex: "#3f6e39", role: "base" },
      { name: "Sprout Lime", hex: "#78aa44", role: "highlight" },
      { name: "Warm White", hex: "#f7f1e6", role: "highlight" },
      { name: "Peach Skin Dark", hex: "#c98263", role: "skin" },
      { name: "Peach Skin Mid", hex: "#e8a987", role: "skin" },
      { name: "Peach Skin Light", hex: "#fad2b8", role: "skin" },
      { name: "Denim Blue Dark", hex: "#233852", role: "clothing" },
      { name: "Denim Blue Mid", hex: "#3e5d7d", role: "clothing" },
      { name: "Denim Blue Light", hex: "#6389a8", role: "clothing" }
    ]
  },
  cozy_farm_16: {
    project: "Cozy Farm 16",
    genre: "Retro Farming",
    camera: "top_down",
    baseTileSize: 16,
    characterScale: 16,
    outlineStyle: "selective",
    palettePolicy: "strict_palette",
    lightingDirection: "top_left",
    shadowPolicy: "warm_brown",
    saturation: "balanced",
    contrast: "high",
    detailDensity: "minimalist",
    animationStyle: "retro_limited",
    uiStyle: "simple_stone",
    backgroundStyle: "flat_retro",
    forbiddenPatterns: ["subpixel_noise", "broken_silhouette"],
    palette: [
      { name: "Night Soil", hex: "#261b17", role: "outline" },
      { name: "Bark Brown", hex: "#593a28", role: "base" },
      { name: "Harvest Gold", hex: "#d49b4b", role: "highlight" },
      { name: "Pasture Green", hex: "#4b823e", role: "base" },
      { name: "Sunny Meadow", hex: "#8db84b", role: "highlight" },
      { name: "Fair Skin Shadow", hex: "#c78665", role: "skin" },
      { name: "Fair Skin Base", hex: "#f0b592", role: "skin" },
      { name: "Apron White", hex: "#f2ece4", role: "clothing" },
      { name: "Water Indigo", hex: "#2f4866", role: "base" },
      { name: "Water Sky", hex: "#5a8bb8", role: "highlight" }
    ]
  },
  topdown_rpg: {
    project: "Topdown Adventure",
    genre: "Classic 16-bit RPG",
    camera: "top_down",
    baseTileSize: 32,
    characterScale: 32,
    outlineStyle: "dark_colored",
    palettePolicy: "ramp_extended",
    lightingDirection: "top_left",
    shadowPolicy: "cool_purple",
    saturation: "balanced",
    contrast: "high",
    detailDensity: "readable_cluster",
    animationStyle: "snappy_chibi",
    uiStyle: "classic_blue_window",
    backgroundStyle: "dungeon_field",
    forbiddenPatterns: ["banded_gradients"],
    palette: [
      { name: "Abyss Navy", hex: "#16152b", role: "outline" },
      { name: "Dungeon Slate", hex: "#353658", role: "shadow" },
      { name: "Steel Silver", hex: "#757999", role: "base" },
      { name: "Plate Polish", hex: "#b5b9db", role: "highlight" },
      { name: "Crimson Cloth", hex: "#8f253b", role: "clothing" },
      { name: "Hero Scarlet", hex: "#c9404f", role: "clothing" },
      { name: "Gold Trim", hex: "#e09f3e", role: "accent" }
    ]
  },
  side_scroll_fantasy: {
    project: "Side Scroll Fantasy",
    genre: "Side-scrolling Action",
    camera: "side_scroller",
    baseTileSize: 32,
    characterScale: 48,
    outlineStyle: "dark_colored",
    palettePolicy: "ramp_extended",
    lightingDirection: "top",
    shadowPolicy: "cool_purple",
    saturation: "vibrant",
    contrast: "high",
    detailDensity: "readable_cluster",
    animationStyle: "bouncy_action",
    uiStyle: "modern_glossy_pixel",
    backgroundStyle: "parallax_deep",
    forbiddenPatterns: ["orphan_pixels"],
    palette: [
      { name: "Deep Royal", hex: "#19112b", role: "outline" },
      { name: "Twilight Violet", hex: "#40265e", role: "shadow" },
      { name: "Luminous Magenta", hex: "#a13b82", role: "base" },
      { name: "Mystic Amber", hex: "#f09837", role: "highlight" },
      { name: "Starlight Yellow", hex: "#ffe46b", role: "accent" }
    ]
  },
  retro_8bit: {
    project: "Retro 8-bit",
    genre: "Famicom Adventure",
    camera: "side_scroller",
    baseTileSize: 16,
    characterScale: 16,
    outlineStyle: "none",
    palettePolicy: "strict_palette",
    lightingDirection: "front",
    shadowPolicy: "direct_tone",
    saturation: "balanced",
    contrast: "high",
    detailDensity: "minimalist",
    animationStyle: "retro_limited",
    uiStyle: "monochrome_box",
    backgroundStyle: "flat_color_blocks",
    forbiddenPatterns: ["semi_transparency", "alpha_blending"],
    palette: [
      { name: "Void Black", hex: "#000000", role: "outline" },
      { name: "Brick Red", hex: "#b81c00", role: "base" },
      { name: "Flesh", hex: "#f87858", role: "skin" },
      { name: "Sky Blue", hex: "#3cbcfc", role: "base" },
      { name: "Pure White", hex: "#ffffff", role: "highlight" }
    ]
  },
  retro_16bit: {
    project: "Retro 16-bit",
    genre: "Super 16-bit RPG",
    camera: "top_down",
    baseTileSize: 16,
    characterScale: 24,
    outlineStyle: "selective",
    palettePolicy: "ramp_extended",
    lightingDirection: "top_left",
    shadowPolicy: "cool_purple",
    saturation: "balanced",
    contrast: "medium",
    detailDensity: "readable_cluster",
    animationStyle: "fluid_smooth",
    uiStyle: "ornate_metallic",
    backgroundStyle: "detailed_tiled",
    forbiddenPatterns: ["broken_outlines"],
    palette: [
      { name: "Deep Charcoal", hex: "#1d1d21", role: "outline" },
      { name: "Bronze Brown", hex: "#634735", role: "base" },
      { name: "Gilding", hex: "#c49a45", role: "highlight" },
      { name: "Moss Green", hex: "#476e38", role: "base" },
      { name: "Meadow Green", hex: "#7fa84e", role: "highlight" }
    ]
  },
  dark_fantasy: {
    project: "Dark Fantasy",
    genre: "Gothic Roguelike",
    camera: "top_down",
    baseTileSize: 32,
    characterScale: 32,
    outlineStyle: "black",
    palettePolicy: "ramp_extended",
    lightingDirection: "top_left",
    shadowPolicy: "desaturated_dark",
    saturation: "muted",
    contrast: "high",
    detailDensity: "high_detail",
    animationStyle: "snappy_chibi",
    uiStyle: "gothic_iron",
    backgroundStyle: "fog_decay",
    forbiddenPatterns: ["neon_colors"],
    palette: [
      { name: "Pitch Black", hex: "#0c0a0d", role: "outline" },
      { name: "Blood Rust", hex: "#421a1f", role: "shadow" },
      { name: "Dried Crimson", hex: "#7a2f35", role: "base" },
      { name: "Bone Gray", hex: "#87837b", role: "base" },
      { name: "Ash Pale", hex: "#bfb8ab", role: "highlight" }
    ]
  },
  bright_adventure: {
    project: "Bright Adventure",
    genre: "Action RPG",
    camera: "top_down",
    baseTileSize: 32,
    characterScale: 32,
    outlineStyle: "dark_colored",
    palettePolicy: "free_harmonized",
    lightingDirection: "top_left",
    shadowPolicy: "warm_brown",
    saturation: "vibrant",
    contrast: "high",
    detailDensity: "readable_cluster",
    animationStyle: "snappy_chibi",
    uiStyle: "bright_gold_border",
    backgroundStyle: "lush_island",
    forbiddenPatterns: ["muddy_colors"],
    palette: [
      { name: "Indigo Dark", hex: "#1e1e38", role: "outline" },
      { name: "Coral Red", hex: "#e84a5f", role: "base" },
      { name: "Sun Yellow", hex: "#ff847c", role: "highlight" },
      { name: "Turquoise Base", hex: "#2a9d8f", role: "base" },
      { name: "Turquoise Glow", hex: "#48cae4", role: "highlight" }
    ]
  },
  minimal_pixel_ui: {
    project: "Minimal UI",
    genre: "Game Interface",
    camera: "top_down",
    baseTileSize: 16,
    characterScale: 16,
    outlineStyle: "dark_colored",
    palettePolicy: "strict_palette",
    lightingDirection: "top",
    shadowPolicy: "desaturated_dark",
    saturation: "balanced",
    contrast: "high",
    detailDensity: "minimalist",
    animationStyle: "retro_limited",
    uiStyle: "clean_modern_frame",
    backgroundStyle: "panel_flat",
    forbiddenPatterns: ["misaligned_borders"],
    palette: [
      { name: "Frame Shadow", hex: "#14171a", role: "outline" },
      { name: "Panel Base", hex: "#222831", role: "base" },
      { name: "Slot Dark", hex: "#1a1f26", role: "shadow" },
      { name: "Bevel Light", hex: "#393e46", role: "highlight" },
      { name: "Accent Amber", hex: "#f39c12", role: "accent" },
      { name: "Warning Red", hex: "#e74c3c", role: "accent" },
      { name: "Text White", hex: "#eeeeee", role: "highlight" }
    ]
  }
};
